// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Web {
	
	
	public partial class AltaSala {
		
		protected System.Web.UI.WebControls.Content menuVerticalContent;
		
		protected Gaia.WebWidgets.ValidationSummary ValidacionAltaSala;
		
		protected Gaia.WebWidgets.Panel pnlMenuVertical;
		
		protected System.Web.UI.WebControls.Menu MenuSalaVertical;
		
		protected System.Web.UI.WebControls.Content contenidoContent;
		
		protected Gaia.WebWidgets.Panel pnlAltaSala;
		
		protected Gaia.WebWidgets.Label lblAltaSala;
		
		protected System.Web.UI.WebControls.Table tblAltaSala;
		
		protected Gaia.WebWidgets.Panel pnlDatosSala;
		
		protected System.Web.UI.WebControls.Table tblDatosSala;
		
		protected System.Web.UI.WebControls.Label lblNombre;
		
		protected Gaia.WebWidgets.TextBox txtNombre;
		
		protected Gaia.WebWidgets.RequiredFieldValidator RequiredNombreAltaSala;
		
		protected System.Web.UI.WebControls.Label lblDescripcion;
		
		protected Gaia.WebWidgets.TextBox txtDescripcion;
		
		protected Gaia.WebWidgets.RequiredFieldValidator RequiredDescripcionAltaSala;
		
		protected System.Web.UI.WebControls.Label lblHabilitado;
		
		protected Gaia.WebWidgets.CheckBox chkHabilitadoAltaSala;
		
		protected Gaia.WebWidgets.Button btnGrabar;
		
		protected Gaia.WebWidgets.Label lblResultadoOperacion;
		
		public new Web.PlantillaMaestra Master {
			get {
				return ((Web.PlantillaMaestra)(base.Master));
			}
		}
	}
}
