// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Web {
	
	
	public partial class InicioSalas {
		
		protected System.Web.UI.WebControls.Content menuVerticalContent;
		
		protected Gaia.WebWidgets.Panel pnlMenuVertical;
		
		protected System.Web.UI.WebControls.Menu MenuSalaVertical;
		
		protected System.Web.UI.WebControls.Content contenidoContent;
		
		protected Gaia.WebWidgets.Panel pnlInicioSala;
		
		protected Gaia.WebWidgets.Label lblAltaSala;
		
		protected System.Web.UI.WebControls.Table tblAltaSala;
		
		protected Gaia.WebWidgets.Panel pnlDatosSala;
		
		protected Gaia.WebWidgets.GridView salasInicioGrid;
		
		protected System.Web.UI.WebControls.ObjectDataSource salasInicioDataSource;
		
		protected Gaia.WebWidgets.Label lblResultadoOperacion;
		
		public new Web.PlantillaMaestra Master {
			get {
				return ((Web.PlantillaMaestra)(base.Master));
			}
		}
	}
}
