// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Web {
	
	
	public partial class AltaFisioterapeuta {
		
		protected System.Web.UI.WebControls.Content menuVerticalContent;
		
		protected Gaia.WebWidgets.Panel pnlMenuVertical;
		
		protected System.Web.UI.WebControls.Menu MenuFisioterapeutaVertical;
		
		protected System.Web.UI.WebControls.Content contenidoContent;
		
		protected Gaia.WebWidgets.Panel pnlAltaFisioterapeuta;
		
		protected Gaia.WebWidgets.Label lblAltaFisioterapeuta;
		
		protected System.Web.UI.WebControls.Table tblAltaFisioterapeuta;
		
		protected Gaia.WebWidgets.Panel pnlDatosFisioterapeuta;
		
		protected System.Web.UI.WebControls.Table tblDatosFisioterapeuta;
		
		protected System.Web.UI.WebControls.Table tblDatosPersonales;
		
		protected System.Web.UI.WebControls.Label lblNombre;
		
		protected Gaia.WebWidgets.TextBox txtNombre;
		
		protected Gaia.WebWidgets.RequiredFieldValidator RequiredNombreAltaFisioterapeuta;
		
		protected System.Web.UI.WebControls.Label lblApellido1;
		
		protected Gaia.WebWidgets.TextBox txtApellido1;
		
		protected Gaia.WebWidgets.RequiredFieldValidator RequiredApellido1AltaFisioterapeuta;
		
		protected System.Web.UI.WebControls.Label lblApellido2;
		
		protected Gaia.WebWidgets.TextBox txtApellido2;
		
		protected System.Web.UI.WebControls.Label lblNIF;
		
		protected Gaia.WebWidgets.TextBox txtNIF;
		
		protected Gaia.WebWidgets.RequiredFieldValidator RequiredNIFAltaFisioterapeuta;
		
		protected System.Web.UI.WebControls.Label lblFechaNacimiento;
		
		protected Gaia.WebWidgets.TextBox txtFechaNacimiento;
		
		protected Gaia.WebWidgets.RequiredFieldValidator RequiredFechaNacimientoAltaFisioterapeuta;
		
		protected System.Web.UI.WebControls.Label lblTelefonoFijo;
		
		protected Gaia.WebWidgets.TextBox txtTelefonoFijo;
		
		protected System.Web.UI.WebControls.Label lblTelefonoMovil;
		
		protected Gaia.WebWidgets.TextBox txtTelefonoMovil;
		
		protected System.Web.UI.WebControls.Label lblEmail;
		
		protected Gaia.WebWidgets.TextBox txtEmail;
		
		protected System.Web.UI.WebControls.Label lblNumeroColegiado;
		
		protected Gaia.WebWidgets.TextBox txtNumeroColegiado;
		
		protected Gaia.WebWidgets.RequiredFieldValidator RequiredNuemeroColegiadoFisioterapeuta;
		
		protected System.Web.UI.WebControls.Label lblFechaTitulacion;
		
		protected Gaia.WebWidgets.TextBox txtFechaTitulacion;
		
		protected Gaia.WebWidgets.RequiredFieldValidator RequiredFechaTitulacionFisioterapeuta;
		
		protected System.Web.UI.WebControls.Label lblFechaIngreso;
		
		protected Gaia.WebWidgets.TextBox txtFechaIngreso;
		
		protected Gaia.WebWidgets.RequiredFieldValidator RequiredFechaIngresoFisioterapeuta;
		
		protected System.Web.UI.WebControls.Label lblTitulaciones;
		
		protected Gaia.WebWidgets.DropDownList ddlTitulaciones;
		
		protected System.Web.UI.WebControls.Label lblTiposContrato;
		
		protected Gaia.WebWidgets.DropDownList ddlTiposContrato;
		
		protected System.Web.UI.WebControls.Label lblProyectoContratacion;
		
		protected Gaia.WebWidgets.DropDownList ddlProyectoContratacion;
		
		protected Gaia.WebWidgets.Panel pnlDireccionFisioterapeuta;
		
		protected System.Web.UI.WebControls.Table tblDatosdireccion;
		
		protected System.Web.UI.WebControls.Label lblVia;
		
		protected Gaia.WebWidgets.TextBox txtVia;
		
		protected Gaia.WebWidgets.RequiredFieldValidator RequiredViaAltaFisioterapeuta;
		
		protected System.Web.UI.WebControls.Label lblNumero;
		
		protected Gaia.WebWidgets.TextBox txtNumeroVia;
		
		protected Gaia.WebWidgets.RequiredFieldValidator RequiredNumerViaAltaFisioterapeuta;
		
		protected System.Web.UI.WebControls.Label lblRestoDireccion;
		
		protected Gaia.WebWidgets.TextBox txtRestoDireccion;
		
		protected System.Web.UI.WebControls.Label lblLocalidad;
		
		protected Gaia.WebWidgets.TextBox txtLocalidad;
		
		protected Gaia.WebWidgets.RequiredFieldValidator RequiredLocalidadAltaFisioterapeuta;
		
		protected System.Web.UI.WebControls.Label lblCP;
		
		protected Gaia.WebWidgets.TextBox txtCP;
		
		protected Gaia.WebWidgets.RequiredFieldValidator RequiredCP;
		
		protected System.Web.UI.WebControls.Label lblProvincia;
		
		protected Gaia.WebWidgets.DropDownList ddlProvincias;
		
		protected Gaia.WebWidgets.Button btnGrabar;
		
		protected Gaia.WebWidgets.ValidationSummary ValidacionAltaFisioterapeuta;
		
		public new Web.PlantillaMaestra Master {
			get {
				return ((Web.PlantillaMaestra)(base.Master));
			}
		}
	}
}
