// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Web.Fisioterapeutas {
	
	
	public partial class BusquedaFisioterapeuta {
		
		protected System.Web.UI.WebControls.Content menuVerticalContent;
		
		protected Gaia.WebWidgets.ValidationSummary ValidacionBusquedaFisioterapeuta;
		
		protected Gaia.WebWidgets.Panel pnlMenuVertical;
		
		protected System.Web.UI.WebControls.Menu MenuFisioterapeutaVertical;
		
		protected System.Web.UI.WebControls.Content contenidoContent;
		
		protected Gaia.WebWidgets.Panel pnlBusquedaFisioterapeuta;
		
		protected Gaia.WebWidgets.Label lblBusquedaFisioterapeuta;
		
		protected System.Web.UI.WebControls.Table tblBusquedaFisioterapeuta;
		
		protected Gaia.WebWidgets.Panel pnlDatosFisioterapeuta;
		
		protected System.Web.UI.WebControls.Table tblDatosFisioterapeuta;
		
		protected System.Web.UI.WebControls.Table tblDatosParticulares;
		
		protected System.Web.UI.WebControls.Label lblNIF;
		
		protected Gaia.WebWidgets.TextBox txtNIF;
		
		protected System.Web.UI.WebControls.Label lblNombre;
		
		protected Gaia.WebWidgets.TextBox txtNombre;
		
		protected System.Web.UI.WebControls.Label lblApellido1;
		
		protected Gaia.WebWidgets.TextBox txtApellido1;
		
		protected System.Web.UI.WebControls.Label lblApellido2;
		
		protected Gaia.WebWidgets.TextBox txtApellido2;
		
		protected Gaia.WebWidgets.Button btnGrabar;
		
		public new Web.PlantillaMaestra Master {
			get {
				return ((Web.PlantillaMaestra)(base.Master));
			}
		}
	}
}
