// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Web.Fisioterapeutas {
	
	
	public partial class MostrarFisioterapeuta {
		
		protected System.Web.UI.WebControls.Content menuVerticalContent;
		
		protected Gaia.WebWidgets.Panel pnlMenuVertical;
		
		protected System.Web.UI.WebControls.Menu MenuPersonaVertical;
		
		protected System.Web.UI.WebControls.Content contenidoContent;
		
		protected Gaia.WebWidgets.Panel pnlMostarFisioterapeuta;
		
		protected Gaia.WebWidgets.Label lblMostarFisioterapeuta;
		
		protected System.Web.UI.WebControls.Table tblMostarFisioterapeuta;
		
		protected Gaia.WebWidgets.Panel pnlDatosFisioterapeuta;
		
		protected System.Web.UI.WebControls.Table tblDatosFisioterapeuta;
		
		protected System.Web.UI.WebControls.Table tblDatosPersonales;
		
		protected System.Web.UI.WebControls.Label lblNombre;
		
		protected Gaia.WebWidgets.TextBox txtNombre;
		
		protected System.Web.UI.WebControls.Label lblApellido1;
		
		protected Gaia.WebWidgets.TextBox txtApellido1;
		
		protected System.Web.UI.WebControls.Label lblApellido2;
		
		protected Gaia.WebWidgets.TextBox txtApellido2;
		
		protected System.Web.UI.WebControls.Label lblNIF;
		
		protected Gaia.WebWidgets.TextBox txtNIF;
		
		protected System.Web.UI.WebControls.Label lblFechaNacimiento;
		
		protected Gaia.WebWidgets.TextBox txtFechaNacimiento;
		
		protected System.Web.UI.WebControls.Label lblTelefonoFijo;
		
		protected Gaia.WebWidgets.TextBox txtTelefonoFijo;
		
		protected System.Web.UI.WebControls.Label lblTelefonoMovil;
		
		protected Gaia.WebWidgets.TextBox txtTelefonoMovil;
		
		protected System.Web.UI.WebControls.Label lblEmail;
		
		protected Gaia.WebWidgets.TextBox txtEmail;
		
		protected System.Web.UI.WebControls.Label lblNumeroColegiado;
		
		protected Gaia.WebWidgets.TextBox txtNumeroColegiado;
		
		protected System.Web.UI.WebControls.Label lblFechaTitulacion;
		
		protected Gaia.WebWidgets.TextBox txtFechaTitulacion;
		
		protected System.Web.UI.WebControls.Label lblFechaIngreso;
		
		protected Gaia.WebWidgets.TextBox txtFechaIngreso;
		
		protected System.Web.UI.WebControls.Label lblFechaBaja;
		
		protected Gaia.WebWidgets.TextBox txtFechaBaja;
		
		protected System.Web.UI.WebControls.Label lblTitulaciones;
		
		protected Gaia.WebWidgets.TextBox txtTitulacion;
		
		protected System.Web.UI.WebControls.Label lblTiposContrato;
		
		protected Gaia.WebWidgets.TextBox txtTipoContrato;
		
		protected Gaia.WebWidgets.Panel pnlDireccionFisioterapeuta;
		
		protected System.Web.UI.WebControls.Table tblDatosdireccion;
		
		protected System.Web.UI.WebControls.Label lblVia;
		
		protected Gaia.WebWidgets.TextBox txtVia;
		
		protected System.Web.UI.WebControls.Label lblNumero;
		
		protected Gaia.WebWidgets.TextBox txtNumeroVia;
		
		protected System.Web.UI.WebControls.Label lblRestoDireccion;
		
		protected Gaia.WebWidgets.TextBox txtRestoDireccion;
		
		protected System.Web.UI.WebControls.Label lblLocalidad;
		
		protected Gaia.WebWidgets.TextBox txtLocalidad;
		
		protected System.Web.UI.WebControls.Label lblCP;
		
		protected Gaia.WebWidgets.TextBox txtCP;
		
		protected System.Web.UI.WebControls.Label lblProvincia;
		
		protected Gaia.WebWidgets.TextBox txtProvincia;
		
		protected Gaia.WebWidgets.Button btnDarBaja;
		
		protected Gaia.WebWidgets.Button btnDarCita;
		
		protected Gaia.WebWidgets.Button btnDarAlta;
		
		public new Web.PlantillaMaestra Master {
			get {
				return ((Web.PlantillaMaestra)(base.Master));
			}
		}
	}
}
