// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Web {
	
	
	public partial class PlantillaMaestra {
		
		protected System.Web.UI.WebControls.Panel pnlCabecera;
		
		protected System.Web.UI.WebControls.Label lblTitulo;
		
		protected System.Web.UI.HtmlControls.HtmlForm formPlantillaMaestra;
		
		protected System.Web.UI.WebControls.Panel pnlMenuHotizontal;
		
		protected System.Web.UI.WebControls.Menu Menu1;
		
		protected System.Web.UI.WebControls.Table tblPlantillaMaestra;
		
		protected System.Web.UI.WebControls.ContentPlaceHolder menuVertical;
		
		protected System.Web.UI.WebControls.ContentPlaceHolder contenido;
	}
}
