// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Web {
	
	
	public partial class AltaPaciente {
		
		protected Gaia.WebWidgets.Panel pnlMenuVertical;
		
		protected System.Web.UI.WebControls.Menu MenuPersonaPacienteVertical;
		
		protected Gaia.WebWidgets.Panel pnlAltaPaciente;
		
		protected Gaia.WebWidgets.Label lblAltaPaciente;
		
		protected System.Web.UI.WebControls.Table tblAltaPaciente;
		
		protected Gaia.WebWidgets.Panel pnlDatosPaciente;
		
		protected System.Web.UI.WebControls.Table tblDatosPaciente;
		
		protected System.Web.UI.WebControls.Table tblDatosParticulares;
		
		protected System.Web.UI.WebControls.Label lblNumeroHistoria;
		
		protected Gaia.WebWidgets.TextBox txtNumeroHistoria;
		
		protected Gaia.WebWidgets.RequiredFieldValidator RequiredNumeroHistoriaAltaPaciente;
		
		protected System.Web.UI.WebControls.Label lblNombre;
		
		protected Gaia.WebWidgets.TextBox txtNombre;
		
		protected Gaia.WebWidgets.RequiredFieldValidator RequiredNombreAltaPaciente;
		
		protected System.Web.UI.WebControls.Label lblApellido1;
		
		protected Gaia.WebWidgets.TextBox txtApellido1;
		
		protected Gaia.WebWidgets.RequiredFieldValidator RequiredApellido1AltaPaciente;
		
		protected System.Web.UI.WebControls.Label lblApellido2;
		
		protected Gaia.WebWidgets.TextBox txtApellido2;
		
		protected System.Web.UI.WebControls.Label lblNIF;
		
		protected Gaia.WebWidgets.TextBox txtNIF;
		
		protected Gaia.WebWidgets.RequiredFieldValidator RequiredNIFAltaPaciente;
		
		protected System.Web.UI.WebControls.Label lblFechaNacimiento;
		
		protected Gaia.WebWidgets.TextBox txtFechaNacimiento;
		
		protected Gaia.WebWidgets.RequiredFieldValidator RequiredFechaNacimientoAltaPaciente;
		
		protected System.Web.UI.WebControls.Label lblTelefonoFijo;
		
		protected Gaia.WebWidgets.TextBox txtTelefonoFijo;
		
		protected System.Web.UI.WebControls.Label lblTelefonoMovil;
		
		protected Gaia.WebWidgets.TextBox txtTelefonoMovil;
		
		protected System.Web.UI.WebControls.Label lblEmail;
		
		protected Gaia.WebWidgets.TextBox txtEmail;
		
		protected System.Web.UI.WebControls.Label lblProfesion;
		
		protected Gaia.WebWidgets.TextBox txtProfesion;
		
		protected System.Web.UI.WebControls.Label lblAficiones;
		
		protected Gaia.WebWidgets.TextBox txtAficiones;
		
		protected Gaia.WebWidgets.RequiredFieldValidator RequiredAficionesAltaPaciente;
		
		protected System.Web.UI.WebControls.Label lblEstudios;
		
		protected Gaia.WebWidgets.DropDownList ddlEstudios;
		
		protected Gaia.WebWidgets.Panel pnlDireccionPaciente;
		
		protected System.Web.UI.WebControls.Table tblDatosdireccion;
		
		protected System.Web.UI.WebControls.Label lblVia;
		
		protected Gaia.WebWidgets.TextBox txtVia;
		
		protected Gaia.WebWidgets.RequiredFieldValidator RequiredViaAltaPaciente;
		
		protected System.Web.UI.WebControls.Label lblNumero;
		
		protected Gaia.WebWidgets.TextBox txtNumeroVia;
		
		protected Gaia.WebWidgets.RequiredFieldValidator RequiredNumerViaAltaPaciente;
		
		protected System.Web.UI.WebControls.Label lblRestoDireccion;
		
		protected Gaia.WebWidgets.TextBox txtRestoDireccion;
		
		protected System.Web.UI.WebControls.Label lblLocalidad;
		
		protected Gaia.WebWidgets.TextBox txtLocalidad;
		
		protected Gaia.WebWidgets.RequiredFieldValidator RequiredLocalidadAltaPaciente;
		
		protected System.Web.UI.WebControls.Label lblCP;
		
		protected Gaia.WebWidgets.TextBox txtCP;
		
		protected Gaia.WebWidgets.RequiredFieldValidator RequiredCP;
		
		protected System.Web.UI.WebControls.Label lblProvincia;
		
		protected Gaia.WebWidgets.DropDownList ddlProvincias;
		
		protected Gaia.WebWidgets.Button btnGrabar;
		
		protected Gaia.WebWidgets.ValidationSummary ValidacionAltaPaciente;
		
		public new Web.PlantillaMaestra Master {
			get {
				return ((Web.PlantillaMaestra)(base.Master));
			}
		}
	}
}
