// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Web.Pacientes {
	
	
	public partial class BusquedaPacientes {
		
		protected System.Web.UI.WebControls.Menu MenuPacienteVertical;
		
		protected System.Web.UI.WebControls.Content contenido;
		
		protected Gaia.WebWidgets.Label lblErrorBusqueda;
		
		protected Gaia.WebWidgets.Label lblBusquedaPaciente;
		
		protected Gaia.WebWidgets.Label lblNIF;
		
		protected Gaia.WebWidgets.TextBox txtNIF;
		
		protected Gaia.WebWidgets.Label lblNombre;
		
		protected Gaia.WebWidgets.TextBox txtNombre;
		
		protected Gaia.WebWidgets.Label lblApellido1;
		
		protected Gaia.WebWidgets.TextBox txtApellido1;
		
		protected Gaia.WebWidgets.Label lblApellido2;
		
		protected Gaia.WebWidgets.TextBox txtApellido2;
		
		protected Gaia.WebWidgets.Label lblHistoriaClinica;
		
		protected Gaia.WebWidgets.TextBox txtHistoriaClinica;
		
		protected Gaia.WebWidgets.Label lblEstudio;
		
		protected Gaia.WebWidgets.DropDownList ddlEstudio;
		
		protected Gaia.WebWidgets.Label lblGrupoTratamiento;
		
		protected Gaia.WebWidgets.DropDownList ddlGruposTratamiento;
		
		protected Gaia.WebWidgets.Label lblEstadoPaciente;
		
		protected Gaia.WebWidgets.DropDownList ddlEstadoPaciente;
		
		protected Gaia.WebWidgets.Button btnGrabar;
		
		protected Gaia.WebWidgets.Panel resultadoBusquedaPacientesPanel;
		
		protected Gaia.WebWidgets.GridView resutadoBusquedaPAcientesGridView;
		
		protected System.Web.UI.WebControls.ObjectDataSource busquedaPacientesDataSource;
		
		protected Gaia.WebWidgets.ValidationSummary ValidacionBusquedaPaciente;
		
		public new Web.PlantillaMaestra Master {
			get {
				return ((Web.PlantillaMaestra)(base.Master));
			}
		}
	}
}
