// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Web.Pacientes {
	
	
	public partial class InicioTratamiento {
		
		protected System.Web.UI.WebControls.Content menuVerticalContent;
		
		protected Gaia.WebWidgets.ValidationSummary ValidacionInicioTratamiento;
		
		protected Gaia.WebWidgets.Panel pnlMenuVertical;
		
		protected System.Web.UI.WebControls.Menu MenuPersonaPacienteVertical;
		
		protected System.Web.UI.WebControls.Content contenidoContent;
		
		protected Gaia.WebWidgets.Panel pnlInicioTratamiento;
		
		protected Gaia.WebWidgets.Label lblBusquedaPaciente;
		
		protected System.Web.UI.WebControls.Table tblParametrosIncialesInicioTratamiento;
		
		protected Gaia.WebWidgets.Panel pnlParametrosInicialesInicioTratamiento;
		
		protected System.Web.UI.WebControls.Table tblDatosPaciente;
		
		protected System.Web.UI.WebControls.Table tblDatosParticulares;
		
		protected System.Web.UI.WebControls.Label lblFisioterapeuta;
		
		protected Gaia.WebWidgets.DropDownList ddlFisioterapeuta;
		
		protected System.Web.UI.WebControls.Label lblEstudio;
		
		protected Gaia.WebWidgets.DropDownList ddlEstudio;
		
		protected System.Web.UI.WebControls.Label lblGrupoTratamiento;
		
		protected Gaia.WebWidgets.TextBox txtGrupoTratamiento;
		
		protected System.Web.UI.WebControls.Label lblNumeroSesionesDefecto;
		
		protected Gaia.WebWidgets.TextBox txtNumeroSesionesDefecto;
		
		protected System.Web.UI.WebControls.Label lblNumeroSesiones;
		
		protected Gaia.WebWidgets.TextBox txtNumeroSesiones;
		
		protected Gaia.WebWidgets.Panel pnlPrimeraValoracion;
		
		protected System.Web.UI.WebControls.Table tblDatosdireccion;
		
		protected System.Web.UI.WebControls.Label lblPrimeraValoracion;
		
		protected Gaia.WebWidgets.TextBox txtVia;
		
		protected Gaia.WebWidgets.Button btnDarCita;
		
		protected Gaia.WebWidgets.Button btnTerminar;
		
		public new Web.PlantillaMaestra Master {
			get {
				return ((Web.PlantillaMaestra)(base.Master));
			}
		}
	}
}
