// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Web {
	
	
	public partial class MostrarPaciente {
		
		protected System.Web.UI.WebControls.Content menuVerticalContent;
		
		protected System.Web.UI.WebControls.Menu MenuPersonaVertical;
		
		protected System.Web.UI.WebControls.Content contenidoContent;
		
		protected Gaia.WebWidgets.Label lblMostrarPaciente;
		
		protected Gaia.WebWidgets.Label lblNombre;
		
		protected Gaia.WebWidgets.TextBox txtNombre;
		
		protected Gaia.WebWidgets.Label lblApellido1;
		
		protected Gaia.WebWidgets.TextBox txtApellido1;
		
		protected Gaia.WebWidgets.Label lblApellido2;
		
		protected Gaia.WebWidgets.TextBox txtApellido2;
		
		protected Gaia.WebWidgets.Label lblNIF;
		
		protected Gaia.WebWidgets.TextBox txtNIF;
		
		protected Gaia.WebWidgets.Label lblFechaNacimiento;
		
		protected Gaia.WebWidgets.TextBox txtFechaNacimiento;
		
		protected Gaia.WebWidgets.Label lblVia;
		
		protected Gaia.WebWidgets.TextBox txtVia;
		
		protected Gaia.WebWidgets.Label lblNumero;
		
		protected Gaia.WebWidgets.TextBox txtNumeroVia;
		
		protected Gaia.WebWidgets.Label lblRestoDireccion;
		
		protected Gaia.WebWidgets.TextBox txtRestoDireccion;
		
		protected Gaia.WebWidgets.Label lblLocalidad;
		
		protected Gaia.WebWidgets.TextBox txtLocalidad;
		
		protected Gaia.WebWidgets.Label lblCP;
		
		protected Gaia.WebWidgets.TextBox txtCP;
		
		protected Gaia.WebWidgets.Label lblProvincia;
		
		protected Gaia.WebWidgets.TextBox txtProvincia;
		
		protected Gaia.WebWidgets.Button btnDarCita;
		
		protected Gaia.WebWidgets.Button btnVerHistorial;
	}
}
