// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Citas {
	
	
	public partial class DarCita {
		
		protected System.Web.UI.WebControls.Content menuVerticalContent;
		
		protected System.Web.UI.WebControls.Menu MenuCitaVertical;
		
		protected System.Web.UI.WebControls.Content contenidoContent;
		
		protected Gaia.WebWidgets.Label lblDarCita;
		
		protected Gaia.WebWidgets.Label lblPaciente;
		
		protected Gaia.WebWidgets.TextBox txtPaciente;
		
		protected Gaia.WebWidgets.Label lblFisioterapeuta;
		
		protected Gaia.WebWidgets.DropDownList ddlFisio;
		
		protected Gaia.WebWidgets.Label lblSala;
		
		protected Gaia.WebWidgets.DropDownList ddlSalas;
		
		protected Gaia.WebWidgets.Label lblTipoCita;
		
		protected Gaia.WebWidgets.RadioButtonList rbTipoCita;
		
		protected Gaia.WebWidgets.Label lblHoraCita;
		
		protected Gaia.WebWidgets.DropDownList ddlHoraCita;
		
		protected Gaia.WebWidgets.Label lblFechaCita;
		
		protected Gaia.WebWidgets.Extensions.DateTimePicker dtpFechaCita;
		
		protected Gaia.WebWidgets.Button btnBuscarCitas;
		
		protected Gaia.WebWidgets.Button btnGrabar;
		
		public new Web.PlantillaMaestra Master {
			get {
				return ((Web.PlantillaMaestra)(base.Master));
			}
		}
	}
}
